### ISSUE TITLE
I keep getting logged out and missing products on minicart

### ISSUE THREAD

**Issue by kubarazny** [rafaelstz/magento2-quicklink#1]
After installation this module on magento, every time I logged into customer account I keep getting logged out, when I went to another page. Additional when i'm on cart page, mini cart shows there's no product in cart and I got error in console like here: https://github.com/GoogleChromeLabs/quicklink/issues/59

**Comment by rafaelstz** [comment]
Hi @kubarazny, thank you for reporting, I'm not able to simulate it using a Magento 2.2.7 instance + sample data, could you provide more information?
Thanks

**Comment by rafaelstz** [comment]
Hi @kubarazny,
It was fixed in the new version that I just released.
Let me know if you have any more issues.
