### ISSUE TITLE
implement service worker to do the caching

### ISSUE THREAD

**Issue by onlinebizsoft** [rafaelstz/magento2-quicklink#29]
Since adding prefetch doesn't work for firefox and safari so I think it would be great if you implement a service worker to do the caching and rendering page from cache which works with any browser.

**Comment by rafaelstz** [comment]
That's an amazing idea, although I have another module that does that, implementing service workers and some PWA minimum features.
I'm going to publish it on Magento Marketplace soon.
Thank you @onlinebizsoft 😁👍

**Comment by onlinebizsoft** [comment]
@rafaelstz you need some helps on testing? 👍
