### ISSUE TITLE
[BUG] Every Page show - "YOU SAVED THE ALERT SUBSCRIPTION" for user logged in

### ISSUE THREAD

**Issue by kfluk** [rafaelstz/magento2-quicklink#30]
**Describe the bug**
When Product Price Alert enabled. All pre-fetch product detail page will show "YOU SAVED THE ALERT SUBSCRIPTION."
It look like pre-fetch load "Notify me when the price drops" link cause the product alert saved.

**To Reproduce**

1. Login to storefront
2. Go to Category / Product Listing
3. Wait 10 seconds for pre-load happens.
4. Click on Any product in viewport.
5. The page will show "YOU SAVED THE ALERT SUBSCRIPTION."

**Expected behavior**
Product detail load without any "YOU SAVED THE ALERT SUBSCRIPTION." appear.

**Screenshots**
![image](https://github.com/rafaelstz/magento2-quicklink/assets/48960528/42b73de8-e27d-4b30-b6e2-48265bfbb030)

**Server (please complete the following information):**
 - Server OS: CentOS 7
 - Magento 2.4.6-p4
 - PHP 8.1
 - Varnish 6.5.2 + Redis 7.2.4 + Elasticsearch 7.17
 - Nginx 1.25

**Test Client (please complete the following information):**
 - Client: Mac OS 14.4
 - Browser: Chrome 123.0, Safari 17.4.1
 - Device: Macbook Pro 16 (2023)

**Additional context**
After disabled Product Alert "Store > Configuration > Catalog > Product Alerts".
The "YOU SAVED THE ALERT SUBSCRIPTION." not show anymore.

**Comment by rafaelstz** [comment]
Hey @kfluk,
You can add an attribute to that link called `noprefetch=true`, it will avoid the link to be prefetched.
