### ISSUE TITLE
Issue with current deps syntax

### ISSUE THREAD

**Issue by antoinekociuba** [rafaelstz/magento2-quicklink#4]
Hi,

For some reasons, I'm getting an error with following _deps_ syntax (object, not array), from _requirejs-config.js_ file: https://github.com/rafaelstz/magento2-quicklink/blob/develop/view/frontend/requirejs-config.js#L13

Error encountered is:

<img width="1426" alt="Capture d’écran 2020-02-08 à 01 16 57" src="https://user-images.githubusercontent.com/1146677/74077225-745dcc80-4a1e-11ea-9405-bb0df1d661e4.png">
<img width="545" alt="Capture d’écran 2020-02-08 à 01 17 21" src="https://user-images.githubusercontent.com/1146677/74077229-7f186180-4a1e-11ea-985e-c9916f57ffc1.png">

I managed to get rid of the errors, by using following syntax:

```
var config = {
    map: {
        '*': {
            quicklink: 'Rafaelcg_Quicklink/js/quicklink.umd',
            polyfillio: 'https://polyfill.io/v2/polyfill.umd.js?features=IntersectionObserver'
        }
    },
    deps: [
        'quicklink'
    ]
};
```

**Comment by rafaelstz** [comment]
Hi @antoinekociuba,
I'm going to remove the `deps`, I don't think it's necessary anymore.

Thank you for your report! 😄

**Comment by antoinekociuba** [comment]
Thanks @rafaelstz !
